# Transmits an authentication request and responds with a discharge macaroon
#
# This is a bit contrived.  I'm not actually performing any authentication.
# The response to this request would be a discharge macaroon.

string principal_name
string resource_name
---
Macaroon discharge_macaroon