# Service to use a resource token
#
# request contains two macaroons:
# 1. a macaroon containing a command from a user to an owner, appended as a first-party caveat,
# 2. a macaroon discharging a third-party authentication caveat in the first macaroon
#
# response simply states whether the command executed successfully

Macaroon command_macaroon
Macaroon discharge_macaroon
---
bool execution_success